### ISSUE TITLE
 System.DllNotFoundException: Unable to load shared library  libffmpeghelper.so

### ISSUE THREAD

**Issue by jwtc-lin** [i-TechSoftware/RtspClientSharpCore#2]
jwtc@jwtc:~/桌面/rtspgetpicture$ sudo dotnet TestRtspClient.dll
Platform Linux 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 X64
Connecting...
Press any key to cancel
Connected.
RtspClientSharpCore.Rtsp.RtspClientException: Receive error
 ---> System.DllNotFoundException: Unable to load shared library '/home/jwtc/桌面/rtspgetpicture/libffmpeghelper.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libavcodec.so.58: cannot open shared object file: No such file or directory
   at FrameDecoderCore.FFmpeg.FFmpegVideoPInvokeLinux.CreateVideoDecoder(FFmpegVideoCodecId videoCodecId, IntPtr& handle)
   at FrameDecoderCore.FFmpeg.FFmpegVideoDecoder.CreateDecoder(FFmpegVideoCodecId videoCodecId) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\FrameDecoderCore\FFmpeg\FFmpegVideoDecoder.cs:line 48
   at TestRtspClient.Program.GetDecoderForFrame(RawVideoFrame videoFrame) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\TestRtspClient\Program.cs:line 185
   at TestRtspClient.Program.RtspClient_FrameReceived(Object sender, RawFrame rawFrame) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\TestRtspClient\Program.cs:line 113
   at RtspClientSharpCore.RtspClient.<CreateRtspClientInternal>b__16_0(RawFrame frame) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\RtspClientSharpCore\RtspClient.cs:line 219
   at RtspClientSharpCore.Rtsp.RtspClientInternal.OnFrameGeneratedLockfree(RawFrame frame) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\RtspClientSharpCore\Rtsp\RtspClientInternal.cs:line 468
   at RtspClientSharpCore.MediaParsers.MediaPayloadParser.OnFrameGenerated(RawFrame e) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\RtspClientSharpCore\MediaParsers\MediaPayloadParser.cs:line 32
   at RtspClientSharpCore.MediaParsers.H264Parser.TryGenerateFrame(ArraySegment`1 frameBytes) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\RtspClientSharpCore\MediaParsers\H264Parser.cs:line 95
   at RtspClientSharpCore.MediaParsers.H264Parser.TryGenerateFrame() in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\RtspClientSharpCore\MediaParsers\H264Parser.cs:line 63
   at RtspClientSharpCore.MediaParsers.H264Parser.Parse(ArraySegment`1 byteSegment, Boolean generateFrame) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\RtspClientSharpCore\MediaParsers\H264Parser.cs:line 53
   at RtspClientSharpCore.MediaParsers.H264VideoPayloadParser.ParseFU(ArraySegment`1 byteSegment, Int32 donFieldSize, Boolean markerBit) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\RtspClientSharpCore\MediaParsers\H264VideoPayloadParser.cs:line 136
   at RtspClientSharpCore.MediaParsers.H264VideoPayloadParser.Parse(TimeSpan timeOffset, ArraySegment`1 byteSegment, Boolean markerBit) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\RtspClientSharpCore\MediaParsers\H264VideoPayloadParser.cs:line 59
   at RtspClientSharpCore.Rtp.RtpStream.ProcessImmediately(RtpPacket& rtpPacket) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\RtspClientSharpCore\Rtp\RtpStream.cs:line 93
   at RtspClientSharpCore.Rtp.RtpStream.Process(ArraySegment`1 payloadSegment) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\RtspClientSharpCore\Rtp\RtpStream.cs:line 45
   at RtspClientSharpCore.Rtsp.RtspClientInternal.ReceiveOverTcpAsync(Stream rtspStream, CancellationToken token) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\RtspClientSharpCore\Rtsp\RtspClientInternal.cs:line 501
   at RtspClientSharpCore.Rtsp.RtspClientInternal.ReceiveAsync(CancellationToken token) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\RtspClientSharpCore\Rtsp\RtspClientInternal.cs:line 130
   at RtspClientSharpCore.RtspClient.ReceiveAsync(CancellationToken token) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\RtspClientSharpCore\RtspClient.cs:line 150
   --- End of inner exception stack trace ---
   at RtspClientSharpCore.RtspClient.ReceiveAsync(CancellationToken token) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\RtspClientSharpCore\RtspClient.cs:line 187
   at TestRtspClient.Program.ConnectAsync(ConnectionParameters connectionParameters, CancellationToken token) in C:\Users\bao-feng\Desktop\RtspClientSharpCore-master\RtspClientSharpCore\TestRtspClient\Program.cs:line 88

**Comment by i-TechSoftware** [comment]
Copy the libffmpeghelper.so library to the application folder or to the library folder (e.g. / usr / lib / ...). If the library is already in the application folder, check its dependencies with the command: 
`ldd libffmpeghelper.so`

**Comment by jwtc-lin** [comment]
jwtc@jwtc:~/桌面/rtspgetpicture$ ldd libffmpeghelper.so
	linux-vdso.so.1 (0x00007ffdc7b69000)
	libavcodec.so.58 => not found
	libavutil.so.56 => not found
	libswscale.so.5 => not found
	libswresample.so.3 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc734551000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc734b46000)

Where are these .SO files downloaded?

**Comment by i-TechSoftware** [comment]
You must install the ffmpeg package version 4.2.1. You can find instructions on installing and configuring the package on the Internet, for example, [here](http://ubuntuhandbook.org/index.php/2019/08/install-ffmpeg-4-2-ubuntu-18-04/)
Also, see the list of all required dependencies in the [README.md](https://github.com/i-TechSoftware/RtspClientSharpCore/blob/master/README.md) file

**Comment by jwtc-lin** [comment]
it work !!Thanks!
How to run in Docker ?

**Comment by i-TechSoftware** [comment]
You are welcome.

> How to run in Docker ?

I don’t know, I didn’t do it
